### PR TITLE
Adding support for audio files on contributions

### PR DESCRIPTION
**Pull request by mstevens83**

### CODE REVIEW

**Comment by mstevens83** [comment]
*TODO*: test case(s)

**Comment by mfc-julius** [comment]
GeoKey uses [semantic versioning](http://semver.org), please add new functionality to new version and patch only the existing methods... And maybe it is better to wrap all new things and release never soon when everything is finished?

Also, for every new feature the documentation website must be updated.

**Comment by mstevens83** [comment]
**Status update**
- Added test cases (on par with those for video)
- Added/fixed supported extensions
- fixed all known issues
- travis builds OK

**Comment by mstevens83** [comment]
**Status update**
- Resolved merge conflict with master
- Added documentation about audio files on website: https://github.com/ExCiteS/geokey-website/pull/19

I'm merging this...

**Pull request merged**
