### PR TITLE
Manage inactive users

### PR DESCRIPTION
**Pull request by oliverroick**
@mfc-julius Please check if it does what it is supposed to

### CODE REVIEW

**Comment by mfc-julius** [comment]
Well, I have no inactive users, apparently. But this should work.

Committed a couple of fixes.

**Comment by mfc-julius** [comment]
Could be also good to see when the user actually registered.

**Comment by oliverroick** [comment]
Feel free to add the info to the template

**Comment by EmpressNaledi** [comment]
@mfc-julius  Having details of when the user registered would be really useful

**Pull request merged**
