### PR TITLE
Dependencies update

### PR DESCRIPTION
**Pull request by mfc-julius**
Updated dependencies + list of software used (on README).

### CODE REVIEW

**Comment by oliverroick** [comment]
What about Pillow and requests?

**Comment by mfc-julius** [comment]
What do you mean?

**Comment by oliverroick** [comment]
The packages don't seem to be updated according to [requires.io](https://requires.io/github/ExCiteS/geokey/requirements/?branch=dependencies-update)

**Comment by mfc-julius** [comment]
Weird, I skipped those somehow.

**Pull request merged**
