### PR TITLE
Use __in filter keyword for Django 1.11

### PR DESCRIPTION
**Pull request by JamesBradbury**
Fix project views for Django 1.11

### CODE REVIEW

**Comment by josokinas** [comment]
Can you give a little more context on this?

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Comment by JamesBradbury** [comment]
This should explain the issue: https://code.djangoproject.com/ticket/25284
Basically the code was relying on a bug/quirky behaviour of the filter which has now been fixed.

**Pull request merged**
